### ISSUE TITLE
关于模型问题？

### ISSUE THREAD

**Issue by minorCoder** [shui-dun/multimodal_ad#2]
想请问一下 作者训练的模型是否开源，可否提供下 我想跑一下数据看看效果

**Comment by shui-dun** [comment]
文章里有说 https://dementia.talkbank.org/access/English/Pitt.html

**Comment by minorCoder** [comment]
> 文章里有说 https://dementia.talkbank.org/access/English/Pitt.html
pitt_audio_and_text_data/ 数据的格式都是需要手动整理的嘛？

**Comment by shui-dun** [comment]
您好，只需按照README（https://github.com/shui-dun/multimodal_ad/tree/master/gnn_based_method ）的做法，整理成以下格式即可：

```
text1 label1
text2 label2
...
textn labeln
```
